
DROP PROCEDURE IF EXISTS UpdateBestSellers;
ALTER TABLE BOOKS
    DROP COLUMN BESTSELLER;
ALTER TABLE BOOKS
    DROP COLUMN RENTS_P_M;
ALTER TABLE BOOKS
    DROP COLUMN TIME_COL;
DELIMITER $$
CREATE PROCEDURE UpdateBestSellers()
BEGIN
    DECLARE MONTHS INT;
    DECLARE BOOKRENTS INT;
    DECLARE B_ID INT;
    DECLARE RENTS_PER_MOUNTH DOUBLE PRECISION(4, 2);
    DECLARE FINISHED INT DEFAULT 0;                 
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    ALTER TABLE BOOKS
        ADD COLUMN BESTSELLER BOOLEAN DEFAULT FALSE;
    ALTER TABLE BOOKS
        ADD COLUMN RENTS_P_M DOUBLE PRECISION(4, 2);
    ALTER TABLE BOOKS
        ADD COLUMN TIME_COL INT;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0)
        DO
            FETCH ALL_BOOKS INTO B_ID;
            IF (FINISHED = 0) THEN
                SELECT COUNT(*) FROM RENTS WHERE BOOK_ID = B_ID INTO BOOKRENTS;

                SELECT TIMESTAMPDIFF(MONTH, MAX(RENT_DATE), MIN(RENT_DATE)) + 1
                FROM RENTS
                WHERE BOOK_ID = B_ID
                INTO MONTHS;
                UPDATE BOOKS SET TIME_COL = MONTHS WHERE BOOK_ID=B_ID ;
                SET RENTS_PER_MOUNTH = BOOKRENTS / MONTHS;
                UPDATE BOOKS SET RENTS_P_M = RENTS_PER_MOUNTH WHERE BOOK_ID = B_ID;

                IF (RENTS_PER_MOUNTH >= 2) THEN
                    UPDATE BOOKS SET BESTSELLER = TRUE WHERE BOOK_ID = B_ID;
                END IF;
            END IF;
        END WHILE;

    CLOSE ALL_BOOKS;
END $$
DELIMITER ;

CALL UpdateBestSellers();
SELECT *
FROM BOOKS;
