
CREATE TABLE READERS_AUD
(
    EVENT_ID       INT(11)  NOT NULL AUTO_INCREMENT,
    EVENT_DATE     DATETIME NOT NULL,
    EVENT_TYPE     VARCHAR(10) DEFAULT NULL,
    READER_ID      INT(11)  NOT NULL,
    OLD_FIRST_NAME VARCHAR(255),
    NEW_FIRST_NAME VARCHAR(255),
    OLD_LASTNAME   VARCHAR(255),
    NEW_LASTNAME   VARCHAR(255),
    OLD_PESELID    VARCHAR(11),
    NEW_PESELID    VARCHAR(11),
    OLD_VIP_LEVEL  VARCHAR(255),
    NEW_VIP_LEVEL  VARCHAR(255),
    PRIMARY KEY (EVENT_ID)
);

DELIMITER $$
CREATE TRIGGER READERS_INSERT
    AFTER INSERT
    ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRST_NAME, NEW_LASTNAME, NEW_PESELID, NEW_VIP_LEVEL)
        VALUE (CURTIME(), "INSERT", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID,NEW.VIP_LEVEL);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER READERS_DELETE
    AFTER DELETE
    ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRST_NAME, OLD_LASTNAME, OLD_PESELID, OLD_VIP_LEVEL)
        VALUE (CURTIME(), "DELETE", OLD.READER_ID, OLD.FIRSTNAME, OLD.LASTNAME, OLD.PESELID,OLD.VIP_LEVEL);
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER READERS_UPDATE
    AFTER UPDATE
    ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRST_NAME,NEW_FIRST_NAME, OLD_LASTNAME,NEW_LASTNAME,
                             OLD_PESELID, NEW_PESELID, OLD_VIP_LEVEL, NEW_VIP_LEVEL)
        VALUE (CURTIME(), "UPDATE",NEW.READER_ID, OLD.FIRSTNAME, NEW.FIRSTNAME,OLD.LASTNAME, NEW.LASTNAME,
               OLD.PESELID, NEW.PESELID,OLD.PESELID,NEW.VIP_LEVEL);
END $$
DELIMITER ;